name: Greeting Workflow

on:
  workflow_dispatch:
    inputs:
      user_name:
        description: 'Name of the user'
        required: true
        default: 'John Doe'
      favorite_color:
        description: 'Favorite color of the user'
        required: true
        default: 'blue'

jobs:
  collect-inputs:
    runs-on: ubuntu-latest
    outputs:
      user_name: ${{ steps.set-outputs.outputs.user_name }}
      favorite_color: ${{ steps.set-outputs.outputs.favorite_color }}
    steps:
      - name: Collect Inputs
        id: set-outputs
        run: |
          echo "user_name=${{ github.event.inputs.user_name }}" >> $GITHUB_OUTPUT
          echo "user_name=${{ github.event.inputs.user_name }}"
          echo "favorite_color=${{ github.event.inputs.favorite_color }}" >> $GITHUB_OUTPUT
          echo "favorite_color=${{ github.event.inputs.favorite_color }}"

  generate-greeting:
    runs-on: ubuntu-latest
    needs: collect-inputs
    outputs:
      greeting: ${{ steps.set-greeting.outputs.greeting }}
    steps:
      - name: Generate Greeting
        id: set-greeting
        run: |
          GREETING="Hello, ${{ needs.collect-inputs.outputs.user_name }}! Your favorite color is ${{ needs.collect-inputs.outputs.favorite_color }}."
          echo "greeting=$GREETING" >> $GITHUB_OUTPUT
          echo "greeting=$GREETING"

  display-greeting:
    runs-on: ubuntu-latest
    needs: generate-greeting
    steps:
      - name: Display Greeting
        run: echo ${{ needs.generate-greeting.outputs.greeting }}
